"""Added relationships

Revision ID: 2a68b115b558
Revises: 8ecc41869f62
Create Date: 2023-09-12 12:52:16.611818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a68b115b558'
down_revision = '8ecc41869f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
