"""Consolidated journal prompts.

Revision ID: 2e6b806ed137
Revises: bfd93dc1e127
Create Date: 2023-09-14 15:36:56.116117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6b806ed137'
down_revision = 'bfd93dc1e127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('career_prompts')
    op.drop_table('relationship_prompts')
    op.drop_table('self_growth_prompts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_growth_prompts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prompt', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_prompts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prompt', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_prompts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prompt', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('journal_prompts')
    # ### end Alembic commands ###
