"""Set up many to many.

Revision ID: 8b505e604e3b
Revises: 2e6b806ed137
Create Date: 2023-09-14 16:01:00.161546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b505e604e3b'
down_revision = '2e6b806ed137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_prompt_id_journal_prompts'), 'journal_prompts', ['prompt_id'], ['id'])
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_prompt_id_journal_prompts'), type_='foreignkey')
        batch_op.drop_column('prompt_id')

    # ### end Alembic commands ###
