"""removed relationships

Revision ID: 95bcb36479d4
Revises: f83e86fd43e6
Create Date: 2023-09-12 14:44:11.824468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bcb36479d4'
down_revision = 'f83e86fd43e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calendar_entries_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_journal_entries_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_journal_entries_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('calendar_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_calendar_entries_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
